# Generated by Django 5.2 on 2025-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
