# Generated by Django 5.2 on 2025-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0002_remove_user_balance_remove_user_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
