# Generated by Django 5.2 on 2025-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
