# Generated by Django 5.2 on 2025-05-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0005_user_balance_user_currency_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.category'),
        ),
    ]
